export interface Kyc {
    phone?: string,
    memberId?: string,
    countryOfResidency?: string,
    phoneCode?: string,
    countryOfCitizenship?: string,
    firstName?: string,
    lastName?: string,
    middleName?: string,
    homeAddress?: string,
    homeAddress2?: string,
    year?: string,
    month?: string,
    day?: string,
    city?: string,
    province?: string,
    postalCode?: string,
    itent?: string,
    source?: string,
    employmentStatus?: string,
    dateOfBirth?: Date,
    revenue?: string,
    industry?: string,
    idType?: string,
    selfieUrls?: string[],
    videoUrl?: string,
    reason?: string,
    idNumber?: string,
    addressProofType?: string,
    addressProofUrl?: string,
    actionRequired?: {
        nationality?: boolean,
        identity?: boolean,
        customerDueDiligence?: boolean,
        document?: boolean
    },
    status?: string
}
